name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'SECURITY.md'
      - 'ios.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 11"

    steps:
      - uses: actions/checkout@v4
      - name: Install XCBeautify
        run: brew install xcbeautify
      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Test platform ${{ matrix.destination }}
	env:
	  scheme: ${{ 'default' }}
        run: |
	  if [ $scheme = default ]; then scheme=$(cat default); fi
	  set -o pipefail && xcodebuild -scheme "$scheme" -destination "${{ matrix.destination }}" test | xcbeautify --renderer github-actions
